### ISSUE TITLE
[ASK] - Fetch page (block) content (h2, bold, images..) 

### ISSUE THREAD

**Issue by DevKylian** [5am-code/laravel-notion-api#162]
Hello,

I want to fetch a content of page (blocks), to create a blog with articles.

My notion structure : 
- 1 full page database contains many pages (articles)
- Each page have a title and content

I'd like to be able to foreach every page in this database and browse the page content.

I was inspired by the code given here:

https://github.com/5am-code/laravel-notion-api/issues/22#issuecomment-871568166

However, while trying to debug the code, I noticed that it was blocking here:

mapTypeToClass() -> fromResponse() from the Block.php class 

Giving me the following error: 

Undefined array key "text"

Do you have any idea where this might be coming from? If you need more information, don't hesitate to ask.

**Comment by johguentner** [comment]
If you want a representation with viewable block-types, I'd recommend this:

```php
Notion::block($blockId)
       ->limit(5) // limit is optional
       ->children()
       ->asCollection();
```

`items` in your case should not be empty. Are you sure you are fetching the correct page? It should have children. Also it will only fetch the direct children, if there are sub-children you have to fetch them block by block. Unfortunately that's limitation we are not able to overcome, due to the Notion API.

**Comment by DevKylian** [comment]
Yes I have a page (blog) with many subpages (articles)

All subpages contains in their body the article content

I try to fetch the content of an article, but it never appears the content of it (only the title)

Do you have the code to retrieve all the body (h1, h2, paragraph..) of a subpage ?

I've been working on it for weeks, but haven't found a way to make it work.

**Comment by johguentner** [comment]
It's quite hard to make a good working script for this without the clear structure.
Could you send over the structure. If it contains personal data, please create a copy of it and replace the personal parts. 

If it's not to complicated I could give you a gist of a script.

**Comment by DevKylian** [comment]
Yes, there is a copy without my private data : 

https://broad-canopy-a87.notion.site/3245b0c7a06d4e67b39deb2207aeb620?v=c405c222a33c41f28c0d6dd30dd6e672&pvs=25

If i'ts more simple, you can move all the articles pages into a database, actually there are on a body of a page

**Comment by johguentner** [comment]
That works for me, if I understand your goal correctly:

```php
//blocks of main page (article pages)
$pages = Notion::block("5b1c65a8ddc5408cb1234ed770959bab")
       ->children()
       ->asCollection();

foreach($pages as $page){
  //blocks of article page
  $blocks = Notion::block($page->getId())
       ->children()
       ->asCollection();

  foreach($blocks as $block){
      //$block -> each block within the article page
  }
}
```

**Comment by DevKylian** [comment]
I try to remove and reinstall the package and it works. 🙏🏻

I must have touched the package code...

Thank's a lot, now I have to succeed to display all the "style" in the html

**Comment by johguentner** [comment]
Perfect! 
Wish you all the best for your project! 💪
