### ISSUE TITLE
Bot users shown as users when calling $user->getObjectType()

### ISSUE THREAD

**Issue by mxrxdxn** [5am-code/laravel-notion-api#164]
**Describe the bug**
When fetching all users from a workspace, integrations/bots are incorrectly shown as "user" instead of "bot". The raw response appears to be correct, but using ->asCollection() sets them as a user.

**To Reproduce**
Laravel 10, PHP 8.1
```php
$notionUsers = \Notion::users()->all()->asCollection();

foreach ($notionUsers as $user) {
    dump($user->getObjectType());
}
```

**Expected behavior**
Users should be set as "user", and bots should be set as "bot", as it is in the raw response.

**Comment by mechelon** [comment]
The method `getObjectType` refers to the `object` key from the response, which is always `user` even if a bot is returned (see https://developers.notion.com/reference/get-users). The `type` key actually contains if a user is a `person` or a `bot`.

To stay with your example, you can access it like this:

 ```php
$notionUsers = \Notion::users()->all()->asCollection();

foreach ($notionUsers as $user) {
    dump($user->getRawResponse()["type"]);
}
```

We may introduce a better getter for this in the future but currently that's the way to go.
