### ISSUE TITLE
RichText function for Notion Page

### ISSUE THREAD

**Issue by vgavrilovikj** [5am-code/laravel-notion-api#22]
Hey, I have some Notion records (pages) where they have properties but also have this text inside the page:
![image](https://user-images.githubusercontent.com/29601489/123801658-c7be0c80-d8ea-11eb-9acf-184c3f7150d9.png)

Reading the Notion API documentation I figured out this is a rich text https://developers.notion.com/reference/rich-text however I am unable to find how to use it..

Do you know if this is supported by the Notion API or not? Because I saw in your code you already have created a RichText property but couldn't find how to call that function.. Thanks!

**Comment by johguentner** [comment]
Hi @vgavrilovikj,
blocks of pages can be retrieved with Notion::block().
You can find details here: https://5amco.de/docs/0.4.0/examples/fetch/blocks

This will help you to read the text within your blocks.

Currently our abstraction allows you to...
- either go through the raw content of the block, which is describe here: https://developers.notion.com/reference/rich-text 
- or to retrieve the plain_text from the raw content

Here a small example (you can try it in Tinkerwell or on your own testpage):
```php
$plainText = "";
$blockCollection = \Notion::block($pageId)->children()->asCollection();
$firstBlock = $blockCollection->first();
if ($firstBlock != null && isset($firstBlock->getRawContent()["text"])) {
	foreach ($firstBlock->getRawContent()["text"] as $rawRichText) {
		$plainText .= $rawRichText["plain_text"] . "\n";
	}
	dd($plainText);
} 
else {
	dd("");
}
```
Detailed block content retrieval is not fully supported yet in the laravel-notion-api, but will be released in the next few days with v0.5.0.

Please be aware, that the notion api itself currently does not support all blocks within notion. Unsupported blocks will have the type "unsupported" and will not provide their content.

**Comment by vgavrilovikj** [comment]
Hey @johguentner thanks for your reply!

Thanks so much for the detailed explanation. I believe this is a FETCH API which only gets the blocks, is there a function that can be used to create a block within a page?

Thanks so much!

**Comment by johguentner** [comment]
Block creation will be added in version v0.5.0 or latest v0.6.0. 
I'll tag the issue as 'feature request', so we'll push updates here as soon as block creation is available within the laravel-notion-api.

**Comment by vgavrilovikj** [comment]
Amazing! Thank you :)
