### ISSUE TITLE
Compound Filters

### ISSUE THREAD

**Issue by keithbrink** [5am-code/laravel-notion-api#49]
I'd like to use the compound filters (currently a TODO comment) when querying a database. Specifically, I would like to use an "and" filter to add two filters at the same time.

Really just opening the issue to give me a place to track it whenever it gets implemented - love this package thanks for all your excellent work on it.

**Comment by mechelon** [comment]
Already working on this one! :)

**Comment by LeeGellie417** [comment]
Any work around on this one?

**Comment by lolocava** [comment]
Hello,
Do you have some news about it ?
This is a key feature.
Thank you !

**Comment by mechelon** [comment]
The implementation of the feature is nearly done, at the moment we are working on proper tests and documentation since this will be a breaking change. We don't want to rush anything, because as you said, it's a key feature.

**Comment by johguentner** [comment]
PR #99 is done by @mechelon and has been merged into ``dev``. 
Will be pushed as ``v1.0.0`` in the next few days.
