### ISSUE TITLE
Syntax error when using PHP 7.4, due to use of union type.

### ISSUE THREAD

**Issue by farez** [5am-code/laravel-notion-api#51]
**Describe the bug**

The union type `float|int` in the function definition of Filter::numberFilter() is flagged as a syntax error, when using PHP 7.4.
 
Union types are only valid in PHP8.0 and above, but PHP 7.4 is being supported in composer.json.

**To Reproduce**
Call Filter::numberFilter() while using PHP 7.4.

**Expected behavior**
There should not be a syntax error.

**Exceptions**
This works fine in PHP8.0. So maybe remove all use of union types or make PHP8.0 the minimum requirement? 

**Additional context**
None.

**Comment by mechelon** [comment]
You're totally right. We will remove the union types for now, as long as 7.4 is still getting security updates, and fix this in the next patch release.
Thank you!

**Comment by farez** [comment]
Great! And you're welcome.
