### ISSUE TITLE
Choose wether time is displayed for date property in page

### ISSUE THREAD

**Issue by rooselle** [5am-code/laravel-notion-api#61]
**Is your feature request related to a problem? Please describe.**
At the moment when a Date property is added to a Page, it's automatically set with date _and_ time, even if time is actually not needed.

**Describe the solution you'd like**
It would be awesome if we could choose wether to display time or not! Because displaying time in Notion when not needed is a bit "polluting".

**Describe alternatives you've considered**
In the meantime I make sure I set my Datetime with 0 in hours, minutes and seconds.

**Additional context**
What I would like:
![image](https://user-images.githubusercontent.com/47738241/151786878-caf8b370-e9b9-441a-80ac-7b8c80cb2b0b.png)
Instead of:
![image](https://user-images.githubusercontent.com/47738241/151786820-b8d6a706-c12e-441e-a493-d7b8409f1f85.png)

**Comment by johguentner** [comment]
Thank you @rooselle for submitting the issue! 
I submitted a PR #69, which fixes this problem.

We will write some final tests, before publishing it as a release (target as version: v0.8.0).

**Comment by johguentner** [comment]
Solved with #77 (Release [v0.8.0 🍉 - Bugfixes, Pagination and General Improvements](https://github.com/5am-code/laravel-notion-api/releases/tag/v0.8.0))
