### ISSUE TITLE
getNextCursor does not exist using Laravel

### ISSUE THREAD

**Issue by DivByZeroIT** [5am-code/laravel-notion-api#81]
Hey hey, 

hope this is not a newbie issue. First of all thanks for the amazing job. I'm having some issues with pagination.

I'm using the package within laravel. When querying a database it seems that the returned results are a Laravel Collection and the method getNextCursor doesn't exist. here's the error I'm getting:

```
 BadMethodCallException 

  Method Illuminate\Support\Collection::getNextCursor does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕ 

```

and my sample code:
```

            if(!$offset)
            {
                $tasks=$notion->database($databaseId)
                ->sortBy($sortings)
                ->limit(5)
                ->query()
                ->asCollection();
            } else {
                $tasks=$notion->database($databaseId)
                ->sortBy($sortings)
                ->offset($offset)
                ->limit(5)
                ->query()
                ->asCollection();
            }

            $offset= $tasks->getNextCursor();
```

Any help would be hugely appreciated :)

**Comment by johguentner** [comment]
Hey @DivByZeroIT,
thank you for using the Laravel Notion API. ✨

Please be aware, that the method ``->getNextCursor()`` is part of the ``PageCollection::class``, which you get after you call ``->query()``.
The method is not included within the ``Collection::class`` of Laravel.
Please make sure to call ``->getNextCursor()``, after you call ``->query()``, not after ``->asCollection()``.

In your example, this would be:
```php
$taskResult = $notion->database($databaseId)
    ->sortBy($sortings)
    ->offset($offset)
    ->limit(5)
    ->query();

$taskCollection = $taskResult->asCollection();
$offset = $taskResult->getNextCursor();
```

Hope this solves your issue 😊

**Comment by DivByZeroIT** [comment]
Hey @johguentner thanks for the super fast response!

Gotcha! Yes I managed to make it work my bad sorry!

Still I was not able to use getNextCursor. Always got:

```
  Call to undefined method FiveamCode\LaravelNotionApi\Entities\Collections\PageCollection::getNextCursor()

  at app/Console/Commands/SyncNotionGoogle.php:72
     68▕                 ->limit(5)
     69▕                 ->query();
     70▕             }
     71▕             print_r($results);
  ➜  72▕             if(!$results->getNextCursor()) $more=false;
     73▕ 
     74▕             $tasks=$results->asCollection();
     75▕ 
     76▕ 
```

it did work with:

`$results->nextCursor()`

**Comment by johguentner** [comment]
Oh yes of course, it's `->nextCursor()`, not `->getNextCursor()`, thanks for checking and confirming that!
Perfect! 👍
