### ISSUE TITLE
Video Embed Block not rendered correctly

### ISSUE THREAD

**Issue by DivByZeroIT** [5am-code/laravel-notion-api#82]
**Describe the bug**
When adding a Youtube Video to a newly created Notion page the block is correctly added with its caption, the origin link sends to the correct video in Youtube, but the youtube player is not rendered correctly:
<img width="1141" alt="CleanShot 2022-09-23 at 07 55 06" src="https://user-images.githubusercontent.com/38038100/191899811-d5c95377-85de-4aa4-a25f-34b90e8dff8f.png">

**To Reproduce**
        $newBlock = Video::create("https://www.youtube.com/watch?v=KLPZzf-wwlE",$video['title']);
        $notion->block($notionPage->getId())->append($newBlock);

**Bonus Quesion**
Is there a way to create the page using a template? :)

Thank you so much for your hard work on this great library

**Comment by johguentner** [comment]
Hey @DivByZeroIT,

Just tried it out with these two lines, and it works for me.

```php
Notion::block("...")
  ->append(Video::create("https://www.youtube.com/watch?v=KLPZzf-wwlE", "Testing Stuff"));
```

Either there was an issue while loading the video, or something else I can't point a finger at currently.
I'm pretty sure it's not a problem with the NotionAPI, but rather some other loading-related issue within Notion. 
The only one issue - which could be produced by the API - is that there is some formatting-error with the URL, which doesn't get resolved correctly when added by the API.
If the error persists, I'd recommend asking Notion directly.

---
As far as I can read into the Notion API Docs, there is no possibility to create pages based on templates. 
As soon as there is, please feel free to open a pull request. :)

**Comment by DivByZeroIT** [comment]
Awesome thanks for the quick response!

My gosh... the problem is the www. I was not passing it. Through Notion it follows the redirect, through API it doesn't. Passing www.youtube.com instead of youtube.com works like a charm.

Thanks!
