### ISSUE TITLE
Bug: Cursor converted to empty object

### ISSUE THREAD

**Issue by fschirinzi** [5am-code/laravel-notion-api#86]
Search-Endpoint while searching using a cursor is broken.

**Here it is correct:**
https://github.com/5am-code/laravel-notion-api/blob/4f75db65b22cb600ffdfba14eab49b1ef36bee54/src/Endpoints/Database.php#L70

**Bug: generates an empty array/object:**
https://github.com/5am-code/laravel-notion-api/blob/20a7fcc7cfce1a479a4218705a179d1d3f48d296/src/Endpoints/Search.php#L64

**Error message**
```
Bad Request: (validation_error) (body failed validation: body.start_cursor should be a string or `undefined`, instead was `{}`.)
```

**Comment by johguentner** [comment]
Fixed with #97 
Release: [v1.0.0](https://github.com/5am-code/laravel-notion-api/releases/tag/v1.0.0)
