### ISSUE TITLE
NotionException returns wrong code

### ISSUE THREAD

**Issue by fschirinzi** [5am-code/laravel-notion-api#89]
**Describe the bug**
When a NotionException is thrown, the code is always `0`.  

**To Reproduce**
No reproduction needed. See code:
https://github.com/5am-code/laravel-notion-api/blob/4f75db65b22cb600ffdfba14eab49b1ef36bee54/src/Exceptions/NotionException.php#L47-L51

**Expected behavior**
The exception should contain the HTTP Status code.

**Exceptions**
.
**Additional context**
.

**See my PR**
https://github.com/5am-code/laravel-notion-api/pull/88

**Comment by johguentner** [comment]
Fixed with #97
